services:
  redis:
    image: redis:7-alpine
    container_name: order_processor_redis
    ports:
      - "6379:6379"
    networks:
      - order_processor_network

  worker:
    deploy:
      mode: replicated
      replicas: ${WORKER_REPLICAS}
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m consumer.worker
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - order_processor_network

networks:
  order_processor_network:
    driver: bridge
